import {Window} from 'happy-dom';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const win=new Window({url:'http://localhost:8765',width:1440,height:1000});
win.document.write(fs.readFileSync(base+'/index.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));
win.fetch=async u=>{const url=new URL(u,'http://localhost:8765');const file=base+url.pathname;return new win.Response(fs.readFileSync(file,'utf8'),{status:200});};
win.alert=()=>{};win.confirm=()=>false;win.scrollTo=()=>{};
win.eval(fs.readFileSync(base+'/assets/leaflet.js','utf8'));
win.eval(fs.readFileSync(base+'/assets/leaflet.markercluster.js','utf8'));
win.eval(fs.readFileSync(base+'/config.js','utf8'));
const script=fs.readFileSync(base+'/index.html','utf8').split('<script>').at(-1).split('</script>')[0];
win.eval(script+'\nwindow.__qa=()=>({marcadores:Object.keys(marcadores).length,datos:datosCache,map,estadoDe,renderizar});');
await new Promise(r=>setTimeout(r,200));
const get=id=>win.document.getElementById(id);
assert.equal(get('cDesc').textContent,'60');assert.equal(get('cOk').textContent,'0');
assert.equal(win.document.querySelectorAll('.stat').length,5);
assert.equal(win.document.querySelectorAll('.tab').length,3);
get('plegar').click();assert.equal(get('contenidoPanel').hidden,true);get('plegar').click();
get('buscar').value='Palmira';get('buscar').dispatchEvent(new win.Event('input'));await new Promise(r=>setTimeout(r,50));
assert.ok(win.__qa().marcadores>0);
const ctx=win.__qa();const now=new Date().toISOString();
assert.equal(ctx.estadoDe('C-31',{estado_datos:'ok',afectados:{'C-31':[]},reporte_fecha:now},true),'afect');
assert.equal(ctx.estadoDe('C-32',{estado_datos:'ok',afectados:{'C-31':[]},reporte_fecha:now},true),'desc');
assert.equal(ctx.estadoDe('C-31',{estado_datos:'ok',afectados:{'C-31':[]},reporte_fecha:'2020-01-01T00:00:00Z'},true),'desc');
assert.equal(ctx.estadoDe('C-31',{estado_datos:'error',afectados:{'C-31':[]},reporte_fecha:now},false),'desc');
const probable={schema:4,estado_datos:'ok',actualizado:now,reporte_fecha:now,afectados:{},programados:{},restablecimientos_probables:{'C-32':{fecha:now,alcance:'deficit',tipo:'inferido',url:'https://t.me/empresaelectricacienfuegos1/1'}}};
assert.equal(ctx.estadoDe('C-32',probable,true),'prob');
assert.equal(ctx.estadoDe('C-32',{...probable,restablecimientos_probables:{'C-32':{fecha:'2020-01-01T00:00:00Z'}}},true),'desc');
assert.equal(ctx.estadoDe('C-32',{schema:4,estado_datos:'ok',reporte_fecha:now,afectados:{'C-32':[]},lectura_incompleta_desde:new Date(Date.now()+1000).toISOString()},true),'afect');
const original=ctx.datos.est;ctx.datos.est=probable;ctx.renderizar();assert.equal(get('cProb').textContent,'1');assert.equal(get('cOk').textContent,'0');
get('buscar').value='';get('buscar').dispatchEvent(new win.Event('input'));win.document.querySelector('.stat.teal').click();assert.equal(get('tourBar').style.display,'flex');get('tourSalir').click();
ctx.datos.est=original;ctx.renderizar();
get('buscar').value='';get('buscar').dispatchEvent(new win.Event('input'));win.document.querySelector('.stat.gray').click();assert.equal(get('tourBar').style.display,'flex');get('tourSalir').click();
console.log('PASS: inicialización con Leaflet real, 60 circuitos sin confirmar, cero verdes ficticios, búsqueda, panel plegable, recorrido, caducidad, restablecimiento probable y estados.');
await win.happyDOM.close();
